/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'trmartines' at '4/12/16 1:07 PM' with Gradle 2.6
 *
 * @author trmartines, @date 4/12/16 1:07 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
